### ISSUE TITLE
raise_order fails on certain periodic geometries

### ISSUE THREAD

**Issue by VikingScientist** [SINTEF/Splipy#22]
```python
from splipy import *                                                           
import splipy.curve_factory as cf                                              
import splipy.surface_factory as sf                                            
                                                                               
crv1 = cf.circle()                                                             
crv2 = cf.n_gon(4) * 3                                                         
srf  = sf.edge_curves(crv1, crv2)                                              
                                                                               
srf.raise_order(0,1)                                                           
```
Crashes with the following output:
```
Traceback (most recent call last):
  File "bug.py", line 9, in <module>
    srf.raise_order(0,1)
  File ".../splipy/SplineObject.py", line 450, in raise_order
    new_bases = [b.raise_order(r) for b, r in zip(self.bases, raises)]
  File ".../splipy/BSplineBasis.py", line 318, in raise_order
    return BSplineBasis(self.order + amount, knots, self.periodic)
  File ".../splipy/BSplineBasis.py", line 57, in __init__
    raise ValueError('knot vector has too few elements')
ValueError: knot vector has too few elements
```

**Comment by VikingScientist** [comment]
Apperently this was fixed in 48a9d13cd7353b9624b20135c0dabb34ecbca949
